<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;


/**
 * Implements hook_ENTITY_TYPE_view().
 */
function lanacion_mvpages_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $nid = $entity->id();
  $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
  $mvp = \Drupal::service('lanacion_mvpages.mostviewedpages');

  if($node->getType() == 'article'){
    $mvp->saveNewView($node);
  }

}
