<?php

/**
 *
 * hook_theme()
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array[]
 */
function lanacion_test_theme($existing, $type, $theme, $path) {

  return [
    'test_custom_theme' => [
      'render element' => 'children',
      'template' => 'test-custom-theme',
      'variables' => [
        'testData' => [],
        'data' => [],
      ],
    ],
  ];

}
